name: SeaDASxCorr
channels:
  - conda-forge
dependencies:
  - mpi4py
  - obspy
  - pip
  - python=3.7
  - numpy
  - numba
  - pycwt
  - pip:
    - zarr
    - tiledb==0.19.0
    - datetime
    - s3fs
    - fsspec